name: Test csvcubed-models on pull request
on:
  pull_request:

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on linux with the newest version of python
        python-version: ['3.11']
        os: [ubuntu-latest, windows-latest]
        include:
          # Test in Linux with Python 3.9
          - os: ubuntu-latest
            python-version: 3.9

    uses: ./.github/workflows/reusable-test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  build_package_and_documentation:
    if: needs.test_in_environments.result == 'success'
    needs: [test_in_environments]
    uses: ./.github/workflows/reusable-build.yaml

  publish_package_and_documentation:
    if: needs.build_package_and_documentation.result == 'success'
    needs: [build_package_and_documentation]
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit